/**
 * Tribe Segmentation, Recommendation and Lake Data Request API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.wordnik.client.model

case class CalenderRecommendation(
  nbxUniqueKey: Option[Int],
  calenderRecoItem: Option[String],
  calenderRecoID: Option[Int])
