import org.apache.spark.sql.SparkSession
import org.apache.spark.sql.Row

//for(i <- 1 to 330) println("a"+i+":String,")

case class T1(a1: String,
              a2: String,
              a3: String,
              a4: String,
              a5: String,
              a6: String,
              a7: String,
              a8: String,
              a9: String,
              a10: String,
              a11: String,
              a12: String,
              a13: String,
              a14: String,
              a15: String,
              a16: String,
              a17: String,
              a18: String,
              a19: String,
              a20: String,
              a21: String,
              a22: String,
              a23: String,
              a24: String,
              a25: String,
              a26: String,
              a27: String,
              a28: String,
              a29: String,
              a30: String,
              a31: String,
              a32: String,
              a33: String,
              a34: String,
              a35: String,
              a36: String,
              a37: String,
              a38: String,
              a39: String,
              a40: String,
              a41: String,
              a42: String,
              a43: String,
              a44: String,
              a45: String,
              a46: String,
              a47: String,
              a48: String,
              a49: String,
              a50: String,
              a51: String,
              a52: String,
              a53: String,
              a54: String,
              a55: String,
              a56: String,
              a57: String,
              a58: String,
              a59: String,
              a60: String,
              a61: String,
              a62: String,
              a63: String,
              a64: String,
              a65: String,
              a66: String,
              a67: String,
              a68: String,
              a69: String,
              a70: String,
              a71: String,
              a72: String,
              a73: String,
              a74: String,
              a75: String,
              a76: String,
              a77: String,
              a78: String,
              a79: String,
              a80: String,
              a81: String,
              a82: String,
              a83: String,
              a84: String,
              a85: String,
              a86: String,
              a87: String,
              a88: String,
              a89: String,
              a90: String,
              a91: String,
              a92: String,
              a93: String,
              a94: String,
              a95: String,
              a96: String,
              a97: String,
              a98: String,
              a99: String,
              a100: String,
              a101: String,
              a102: String,
              a103: String,
              a104: String,
              a105: String,
              a106: String,
              a107: String,
              a108: String,
              a109: String,
              a110: String,
              a111: String,
              a112: String,
              a113: String,
              a114: String,
              a115: String,
              a116: String,
              a117: String,
              a118: String,
              a119: String,
              a120: String,
              a121: String,
              a122: String,
              a123: String,
              a124: String,
              a125: String,
              a126: String,
              a127: String,
              a128: String,
              a129: String,
              a130: String,
              a131: String,
              a132: String,
              a133: String,
              a134: String,
              a135: String,
              a136: String,
              a137: String,
              a138: String,
              a139: String,
              a140: String,
              a141: String,
              a142: String,
              a143: String,
              a144: String,
              a145: String,
              a146: String,
              a147: String,
              a148: String,
              a149: String,
              a150: String,
              a151: String,
              a152: String,
              a153: String,
              a154: String,
              a155: String,
              a156: String,
              a157: String,
              a158: String,
              a159: String,
              a160: String,
              a161: String,
              a162: String,
              a163: String,
              a164: String,
              a165: String,
              a166: String,
              a167: String,
              a168: String,
              a169: String,
              a170: String,
              a171: String,
              a172: String,
              a173: String,
              a174: String,
              a175: String,
              a176: String,
              a177: String,
              a178: String,
              a179: String,
              a180: String,
              a181: String,
              a182: String,
              a183: String,
              a184: String,
              a185: String,
              a186: String,
              a187: String,
              a188: String,
              a189: String,
              a190: String,
              a191: String,
              a192: String,
              a193: String,
              a194: String,
              a195: String,
              a196: String,
              a197: String,
              a198: String,
              a199: String,
              a200: String,
              a201: String,
              a202: String,
              a203: String,
              a204: String,
              a205: String,
              a206: String,
              a207: String,
              a208: String,
              a209: String,
              a210: String,
              a211: String,
              a212: String,
              a213: String,
              a214: String,
              a215: String,
              a216: String,
              a217: String,
              a218: String,
              a219: String,
              a220: String,
              a221: String,
              a222: String,
              a223: String,
              a224: String,
              a225: String,
              a226: String,
              a227: String,
              a228: String,
              a229: String,
              a230: String,
              a231: String,
              a232: String,
              a233: String,
              a234: String,
              a235: String,
              a236: String,
              a237: String,
              a238: String,
              a239: String,
              a240: String,
              a241: String,
              a242: String,
              a243: String,
              a244: String,
              a245: String,
              a246: String,
              a247: String,
              a248: String,
              a249: String,
              a250: String,
              a251: String,
              a252: String,
              a253: String,
              a254: String,
              a255: String,
              a256: String,
              a257: String,
              a258: String,
              a259: String,
              a260: String,
              a261: String,
              a262: String,
              a263: String,
              a264: String,
              a265: String,
              a266: String,
              a267: String,
              a268: String,
              a269: String,
              a270: String,
              a271: String,
              a272: String,
              a273: String,
              a274: String,
              a275: String,
              a276: String,
              a277: String,
              a278: String,
              a279: String,
              a280: String,
              a281: String,
              a282: String,
              a283: String,
              a284: String,
              a285: String,
              a286: String,
              a287: String,
              a288: String,
              a289: String,
              a290: String,
              a291: String,
              a292: String,
              a293: String,
              a294: String,
              a295: String,
              a296: String,
              a297: String,
              a298: String,
              a299: String,
              a300: String,
              a301: String,
              a302: String,
              a303: String,
              a304: String,
              a305: String,
              a306: String,
              a307: String,
              a308: String,
              a309: String,
              a310: String,
              a311: String,
              a312: String,
              a313: String,
              a314: String,
              a315: String,
              a316: String,
              a317: String,
              a318: String,
              a319: String,
              a320: String,
              a321: String,
              a322: String,
              a323: String,
              a324: String,
              a325: String,
              a326: String,
              a327: String,
              a328: String,
              a329: String,
              a330: String)

object Test {
  def main(args: Array[String]): Unit = {
    val sparkSql = SparkSession.builder().appName("Test").master("local[*]").getOrCreate()
    import sparkSql.implicits._
    val df = sparkSql.read.json("test1.json")
    //for(i <- 1 to 330) println("removeNull(x.getAs[String]("+i+")),")

    val res = df.map {
      x =>
        T1(removeNull(x.getAs[String](1)),
          removeNull(x.getAs[String](2)),
          removeNull(x.getAs[String](3)),
          removeNull(x.getAs[String](4)),
          removeNull(x.getAs[String](5)),
          removeNull(x.getAs[String](6)),
          removeNull(x.getAs[String](7)),
          removeNull(x.getAs[String](8)),
          removeNull(x.getAs[String](9)),
          removeNull(x.getAs[String](10)),
          removeNull(x.getAs[String](11)),
          removeNull(x.getAs[String](12)),
          removeNull(x.getAs[String](13)),
          removeNull(x.getAs[String](14)),
          removeNull(x.getAs[String](15)),
          removeNull(x.getAs[String](16)),
          removeNull(x.getAs[String](17)),
          removeNull(x.getAs[String](18)),
          removeNull(x.getAs[String](19)),
          removeNull(x.getAs[String](20)),
          removeNull(x.getAs[String](21)),
          removeNull(x.getAs[String](22)),
          removeNull(x.getAs[String](23)),
          removeNull(x.getAs[String](24)),
          removeNull(x.getAs[String](25)),
          removeNull(x.getAs[String](26)),
          removeNull(x.getAs[String](27)),
          removeNull(x.getAs[String](28)),
          removeNull(x.getAs[String](29)),
          removeNull(x.getAs[String](30)),
          removeNull(x.getAs[String](31)),
          removeNull(x.getAs[String](32)),
          removeNull(x.getAs[String](33)),
          removeNull(x.getAs[String](34)),
          removeNull(x.getAs[String](35)),
          removeNull(x.getAs[String](36)),
          removeNull(x.getAs[String](37)),
          removeNull(x.getAs[String](38)),
          removeNull(x.getAs[String](39)),
          removeNull(x.getAs[String](40)),
          removeNull(x.getAs[String](41)),
          removeNull(x.getAs[String](42)),
          removeNull(x.getAs[String](43)),
          removeNull(x.getAs[String](44)),
          removeNull(x.getAs[String](45)),
          removeNull(x.getAs[String](46)),
          removeNull(x.getAs[String](47)),
          removeNull(x.getAs[String](48)),
          removeNull(x.getAs[String](49)),
          removeNull(x.getAs[String](50)),
          removeNull(x.getAs[String](51)),
          removeNull(x.getAs[String](52)),
          removeNull(x.getAs[String](53)),
          removeNull(x.getAs[String](54)),
          removeNull(x.getAs[String](55)),
          removeNull(x.getAs[String](56)),
          removeNull(x.getAs[String](57)),
          removeNull(x.getAs[String](58)),
          removeNull(x.getAs[String](59)),
          removeNull(x.getAs[String](60)),
          removeNull(x.getAs[String](61)),
          removeNull(x.getAs[String](62)),
          removeNull(x.getAs[String](63)),
          removeNull(x.getAs[String](64)),
          removeNull(x.getAs[String](65)),
          removeNull(x.getAs[String](66)),
          removeNull(x.getAs[String](67)),
          removeNull(x.getAs[String](68)),
          removeNull(x.getAs[String](69)),
          removeNull(x.getAs[String](70)),
          removeNull(x.getAs[String](71)),
          removeNull(x.getAs[String](72)),
          removeNull(x.getAs[String](73)),
          removeNull(x.getAs[String](74)),
          removeNull(x.getAs[String](75)),
          removeNull(x.getAs[String](76)),
          removeNull(x.getAs[String](77)),
          removeNull(x.getAs[String](78)),
          removeNull(x.getAs[String](79)),
          removeNull(x.getAs[String](80)),
          removeNull(x.getAs[String](81)),
          removeNull(x.getAs[String](82)),
          removeNull(x.getAs[String](83)),
          removeNull(x.getAs[String](84)),
          removeNull(x.getAs[String](85)),
          removeNull(x.getAs[String](86)),
          removeNull(x.getAs[String](87)),
          removeNull(x.getAs[String](88)),
          removeNull(x.getAs[String](89)),
          removeNull(x.getAs[String](90)),
          removeNull(x.getAs[String](91)),
          removeNull(x.getAs[String](92)),
          removeNull(x.getAs[String](93)),
          removeNull(x.getAs[String](94)),
          removeNull(x.getAs[String](95)),
          removeNull(x.getAs[String](96)),
          removeNull(x.getAs[String](97)),
          removeNull(x.getAs[String](98)),
          removeNull(x.getAs[String](99)),
          removeNull(x.getAs[String](100)),
          removeNull(x.getAs[String](101)),
          removeNull(x.getAs[String](102)),
          removeNull(x.getAs[String](103)),
          removeNull(x.getAs[String](104)),
          removeNull(x.getAs[String](105)),
          removeNull(x.getAs[String](106)),
          removeNull(x.getAs[String](107)),
          removeNull(x.getAs[String](108)),
          removeNull(x.getAs[String](109)),
          removeNull(x.getAs[String](110)),
          removeNull(x.getAs[String](111)),
          removeNull(x.getAs[String](112)),
          removeNull(x.getAs[String](113)),
          removeNull(x.getAs[String](114)),
          removeNull(x.getAs[String](115)),
          removeNull(x.getAs[String](116)),
          removeNull(x.getAs[String](117)),
          removeNull(x.getAs[String](118)),
          removeNull(x.getAs[String](119)),
          removeNull(x.getAs[String](120)),
          removeNull(x.getAs[String](121)),
          removeNull(x.getAs[String](122)),
          removeNull(x.getAs[String](123)),
          removeNull(x.getAs[String](124)),
          removeNull(x.getAs[String](125)),
          removeNull(x.getAs[String](126)),
          removeNull(x.getAs[String](127)),
          removeNull(x.getAs[String](128)),
          removeNull(x.getAs[String](129)),
          removeNull(x.getAs[String](130)),
          removeNull(x.getAs[String](131)),
          removeNull(x.getAs[String](132)),
          removeNull(x.getAs[String](133)),
          removeNull(x.getAs[String](134)),
          removeNull(x.getAs[String](135)),
          removeNull(x.getAs[String](136)),
          removeNull(x.getAs[String](137)),
          removeNull(x.getAs[String](138)),
          removeNull(x.getAs[String](139)),
          removeNull(x.getAs[String](140)),
          removeNull(x.getAs[String](141)),
          removeNull(x.getAs[String](142)),
          removeNull(x.getAs[String](143)),
          removeNull(x.getAs[String](144)),
          removeNull(x.getAs[String](145)),
          removeNull(x.getAs[String](146)),
          removeNull(x.getAs[String](147)),
          removeNull(x.getAs[String](148)),
          removeNull(x.getAs[String](149)),
          removeNull(x.getAs[String](150)),
          removeNull(x.getAs[String](151)),
          removeNull(x.getAs[String](152)),
          removeNull(x.getAs[String](153)),
          removeNull(x.getAs[String](154)),
          removeNull(x.getAs[String](155)),
          removeNull(x.getAs[String](156)),
          removeNull(x.getAs[String](157)),
          removeNull(x.getAs[String](158)),
          removeNull(x.getAs[String](159)),
          removeNull(x.getAs[String](160)),
          removeNull(x.getAs[String](161)),
          removeNull(x.getAs[String](162)),
          removeNull(x.getAs[String](163)),
          removeNull(x.getAs[String](164)),
          removeNull(x.getAs[String](165)),
          removeNull(x.getAs[String](166)),
          removeNull(x.getAs[String](167)),
          removeNull(x.getAs[String](168)),
          removeNull(x.getAs[String](169)),
          removeNull(x.getAs[String](170)),
          removeNull(x.getAs[String](171)),
          removeNull(x.getAs[String](172)),
          removeNull(x.getAs[String](173)),
          removeNull(x.getAs[String](174)),
          removeNull(x.getAs[String](175)),
          removeNull(x.getAs[String](176)),
          removeNull(x.getAs[String](177)),
          removeNull(x.getAs[String](178)),
          removeNull(x.getAs[String](179)),
          removeNull(x.getAs[String](180)),
          removeNull(x.getAs[String](181)),
          removeNull(x.getAs[String](182)),
          removeNull(x.getAs[String](183)),
          removeNull(x.getAs[String](184)),
          removeNull(x.getAs[String](185)),
          removeNull(x.getAs[String](186)),
          removeNull(x.getAs[String](187)),
          removeNull(x.getAs[String](188)),
          removeNull(x.getAs[String](189)),
          removeNull(x.getAs[String](190)),
          removeNull(x.getAs[String](191)),
          removeNull(x.getAs[String](192)),
          removeNull(x.getAs[String](193)),
          removeNull(x.getAs[String](194)),
          removeNull(x.getAs[String](195)),
          removeNull(x.getAs[String](196)),
          removeNull(x.getAs[String](197)),
          removeNull(x.getAs[String](198)),
          removeNull(x.getAs[String](199)),
          removeNull(x.getAs[String](200)),
          removeNull(x.getAs[String](201)),
          removeNull(x.getAs[String](202)),
          removeNull(x.getAs[String](203)),
          removeNull(x.getAs[String](204)),
          removeNull(x.getAs[String](205)),
          removeNull(x.getAs[String](206)),
          removeNull(x.getAs[String](207)),
          removeNull(x.getAs[String](208)),
          removeNull(x.getAs[String](209)),
          removeNull(x.getAs[String](210)),
          removeNull(x.getAs[String](211)),
          removeNull(x.getAs[String](212)),
          removeNull(x.getAs[String](213)),
          removeNull(x.getAs[String](214)),
          removeNull(x.getAs[String](215)),
          removeNull(x.getAs[String](216)),
          removeNull(x.getAs[String](217)),
          removeNull(x.getAs[String](218)),
          removeNull(x.getAs[String](219)),
          removeNull(x.getAs[String](220)),
          removeNull(x.getAs[String](221)),
          removeNull(x.getAs[String](222)),
          removeNull(x.getAs[String](223)),
          removeNull(x.getAs[String](224)),
          removeNull(x.getAs[String](225)),
          removeNull(x.getAs[String](226)),
          removeNull(x.getAs[String](227)),
          removeNull(x.getAs[String](228)),
          removeNull(x.getAs[String](229)),
          removeNull(x.getAs[String](230)),
          removeNull(x.getAs[String](231)),
          removeNull(x.getAs[String](232)),
          removeNull(x.getAs[String](233)),
          removeNull(x.getAs[String](234)),
          removeNull(x.getAs[String](235)),
          removeNull(x.getAs[String](236)),
          removeNull(x.getAs[String](237)),
          removeNull(x.getAs[String](238)),
          removeNull(x.getAs[String](239)),
          removeNull(x.getAs[String](240)),
          removeNull(x.getAs[String](241)),
          removeNull(x.getAs[String](242)),
          removeNull(x.getAs[String](243)),
          removeNull(x.getAs[String](244)),
          removeNull(x.getAs[String](245)),
          removeNull(x.getAs[String](246)),
          removeNull(x.getAs[String](247)),
          removeNull(x.getAs[String](248)),
          removeNull(x.getAs[String](249)),
          removeNull(x.getAs[String](250)),
          removeNull(x.getAs[String](251)),
          removeNull(x.getAs[String](252)),
          removeNull(x.getAs[String](253)),
          removeNull(x.getAs[String](254)),
          removeNull(x.getAs[String](255)),
          removeNull(x.getAs[String](256)),
          removeNull(x.getAs[String](257)),
          removeNull(x.getAs[String](258)),
          removeNull(x.getAs[String](259)),
          removeNull(x.getAs[String](260)),
          removeNull(x.getAs[String](261)),
          removeNull(x.getAs[String](262)),
          removeNull(x.getAs[String](263)),
          removeNull(x.getAs[String](264)),
          removeNull(x.getAs[String](265)),
          removeNull(x.getAs[String](266)),
          removeNull(x.getAs[String](267)),
          removeNull(x.getAs[String](268)),
          removeNull(x.getAs[String](269)),
          removeNull(x.getAs[String](270)),
          removeNull(x.getAs[String](271)),
          removeNull(x.getAs[String](272)),
          removeNull(x.getAs[String](273)),
          removeNull(x.getAs[String](274)),
          removeNull(x.getAs[String](275)),
          removeNull(x.getAs[String](276)),
          removeNull(x.getAs[String](277)),
          removeNull(x.getAs[String](278)),
          removeNull(x.getAs[String](279)),
          removeNull(x.getAs[String](280)),
          removeNull(x.getAs[String](281)),
          removeNull(x.getAs[String](282)),
          removeNull(x.getAs[String](283)),
          removeNull(x.getAs[String](284)),
          removeNull(x.getAs[String](285)),
          removeNull(x.getAs[String](286)),
          removeNull(x.getAs[String](287)),
          removeNull(x.getAs[String](288)),
          removeNull(x.getAs[String](289)),
          removeNull(x.getAs[String](290)),
          removeNull(x.getAs[String](291)),
          removeNull(x.getAs[String](292)),
          removeNull(x.getAs[String](293)),
          removeNull(x.getAs[String](294)),
          removeNull(x.getAs[String](295)),
          removeNull(x.getAs[String](296)),
          removeNull(x.getAs[String](297)),
          removeNull(x.getAs[String](298)),
          removeNull(x.getAs[String](299)),
          removeNull(x.getAs[String](300)),
          removeNull(x.getAs[String](301)),
          removeNull(x.getAs[String](302)),
          removeNull(x.getAs[String](303)),
          removeNull(x.getAs[String](304)),
          removeNull(x.getAs[String](305)),
          removeNull(x.getAs[String](306)),
          removeNull(x.getAs[String](307)),
          removeNull(x.getAs[String](308)),
          removeNull(x.getAs[String](309)),
          removeNull(x.getAs[String](310)),
          removeNull(x.getAs[String](311)),
          removeNull(x.getAs[String](312)),
          removeNull(x.getAs[String](313)),
          removeNull(x.getAs[String](314)),
          removeNull(x.getAs[String](315)),
          removeNull(x.getAs[String](316)),
          removeNull(x.getAs[String](317)),
          removeNull(x.getAs[String](318)),
          removeNull(x.getAs[String](319)),
          removeNull(x.getAs[String](320)),
          removeNull(x.getAs[String](321)),
          removeNull(x.getAs[String](322)),
          removeNull(x.getAs[String](323)),
          removeNull(x.getAs[String](324)),
          removeNull(x.getAs[String](325)),
          removeNull(x.getAs[String](326)),
          removeNull(x.getAs[String](327)),
          removeNull(x.getAs[String](328)),
          removeNull(x.getAs[String](329)),
          removeNull(x.getAs[String](330)))
    }
    //    val coll=res.collect()
    //    df.write.parquet("out1.parquet")
    //    df.printSchema()
    //    sparkSql.close()
  }

  def removeNull(str: String) = str.replace("NULL", "0")

}